# SITE CONFIGURATION
baseurl: "/dsportfolio"
url: "https://jessidub.github.io/"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Jessica (Lifang) Wang
  avatar: assets/img/avatar1.png
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash
  description: "A data science portfolio" # used by search engines
  site_navigation_sort: 'order'

  # Header and footer text
  header_text: >
     <p>This is where I dump things from my brain</p>

     <p> Lalalalala~~~</p>
  header_text_feature_image: assets/img/sample_feature_img.png
  footer_text: >
   Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/rohanchandra/type-theme">Type Theme</a>

  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: "JessiDub/dsportfolio"
  gitter:
  google_plus:
  instagram:
  linkedin:  "https://www.linkedin.com/in/jessica-lifang-wang"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup
  search: true # Enable the search feature

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."
  str_search_no_results: "No results found."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
exclude:
  - Gemfile
  - Gemfile.lock
